CLIENT_ID = "CLIENT_ID"
CLIENT_SECRET = "CLIENT_SECRET"
USERNAME = "SPOTIFY_USERNAME"
REDIRECT_URL = "http://localhost/callback"
PLAYLIST_ID = "PLAYLIST_ID"
SCOPE = "playlist-modify-public user-top-read"
